name: Terraform CI

on: [pull_request]

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: terraform fmt check
        run: terraform fmt -check

      - name: init & plan
        run: |
          terraform init -backend=false
          terraform validate
          terraform plan -no-color

